version: '3.7'
services:
  app:
    build: .
    #command: python -u initialize_app.py
    command: gunicorn --bind 0.0.0.0:5000 -w 1 --threads 100 wsgi:app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - mongo_db_volume:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_db_volume:
